name: monkey
description: Monkey interpreter for Dart.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0

dependencies:
  meta: ^1.7.0
  tuple: ^2.0.0
