name: monkey
description: Monkey interpreter for Dart.
version: 0.1.0

environment:
  sdk: ">=2.13.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  meta: ^1.7.0
  tuple: ^2.0.0
