name: Dart

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]

jobs:
  format-and-analyze-and-test:
    runs-on: ubuntu-latest
    container:
      image: dart:3.5.4

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: pub get

      - name: dartfmt
        run: dart format . --output=none --set-exit-if-changed

      - name: analyzer
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: test
        run: pub run test ./
